name: Build

on:
  push:
    branches: [ master ]
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
  build-linux-x86_64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: |
        sudo apt install -y musl-tools
        rustup target add x86_64-unknown-linux-musl
    - name: Build linux-x86_64
      run: |
        cargo build --verbose --release --target=x86_64-unknown-linux-musl
        strip target/x86_64-unknown-linux-musl/release/objtalk-server
        strip target/x86_64-unknown-linux-musl/release/objtalk-cli
        tar cfvz objtalk-linux-x86_64.tar.gz -C target/x86_64-unknown-linux-musl/release objtalk-server objtalk-cli
    - uses: actions/upload-artifact@v2
      with:
        name: objtalk-linux-x86_64.tar.gz
        path: objtalk-linux-x86_64.tar.gz
  build-linux-x86:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: |
        sudo apt install -y musl-tools
        rustup target add i686-unknown-linux-musl
    - name: Build linux-x86
      run: |
        cargo build --verbose --release --target=i686-unknown-linux-musl
        strip target/i686-unknown-linux-musl/release/objtalk-server
        strip target/i686-unknown-linux-musl/release/objtalk-cli
        tar cfvz objtalk-linux-x86.tar.gz -C target/i686-unknown-linux-musl/release objtalk-server objtalk-cli
    - uses: actions/upload-artifact@v2
      with:
        name: objtalk-linux-x86.tar.gz
        path: objtalk-linux-x86.tar.gz
  build-linux-armv7:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: cargo install cross
    - name: Build linux-armv7
      run: |
        cross build --verbose --release --target=armv7-unknown-linux-musleabihf
        tar cfvz objtalk-linux-armv7.tar.gz -C target/armv7-unknown-linux-musleabihf/release objtalk-server objtalk-cli
    - uses: actions/upload-artifact@v2
      with:
        name: objtalk-linux-armv7.tar.gz
        path: objtalk-linux-armv7.tar.gz
  release:
    runs-on: ubuntu-latest
    needs: [test, build-linux-x86_64, build-linux-x86, build-linux-armv7]
    steps:
    - uses: actions/download-artifact@v2
    - name: Release Development Build
      if: "!startsWith(github.ref, 'refs/tags/v')"
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          objtalk-linux-x86_64.tar.gz
          objtalk-linux-x86.tar.gz
          objtalk-linux-armv7.tar.gz
    - name: Release Build
      if: startsWith(github.ref, 'refs/tags/v')
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: false
        files: |
          objtalk-linux-x86_64.tar.gz
          objtalk-linux-x86.tar.gz
          objtalk-linux-armv7.tar.gz
