name: Release Build

on:
  tags:
    - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: |
        sudo apt install -y musl-tools
        rustup target add x86_64-unknown-linux-musl
    - name: Run tests
      run: cargo test --verbose
    - name: Build linux-x86_64
      run: |
        cargo build --verbose --release --target=x86_64-unknown-linux-musl
        strip target/x86_64-unknown-linux-musl/release/objtalk-server
        strip target/x86_64-unknown-linux-musl/release/objtalk-cli
        tar cfvz objtalk-linux-x86_64.tar.gz -C target/x86_64-unknown-linux-musl/release objtalk-server objtalk-cli
    - name: Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: false
        files: |
          objtalk-linux-x86_64.tar.gz
